name: Claude Deployment Failure Reviewer

permissions:
  contents: read
  pull-requests: write
  actions: read
  id-token: write

on:
  workflow_run:
    workflows: ["*"]
    types: [completed]

jobs:
  claude-deployment-review:
    if: github.event.workflow_run.conclusion == 'failure'
    runs-on: ubuntu-latest
    env:
      AWS_REGION: eu-central-1
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Generate GitHub App token
        id: app-token
        uses: actions/create-github-app-token@v2
        with:
          app-id: ${{ secrets.APP_ID }}
          private-key: ${{ secrets.APP_PRIVATE_KEY }}

      - name: Configure AWS Credentials (OIDC)
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_TO_ASSUME }}
          aws-region: eu-central-1

      - uses: anthropics/claude-code-action@v1
        with:
          github_token: ${{ steps.app-token.outputs.token }}
          use_bedrock: "true"
          track_progress: true
          prompt: |
            REPO: ${{ github.repository }}
            FAILED WORKFLOW: ${{ github.event.workflow_run.name }}
            WORKFLOW RUN ID: ${{ github.event.workflow_run.id }}
            PR NUMBER: ${{ github.event.workflow_run.pull_requests[0].number }}

            You are a deployment expert analyzing a failed GitHub Actions workflow.
            
            Please:
            1. Inspect the failed workflow logs and identify the root cause
            2. Examine the code changes in the associated PR that may have caused the failure
            3. Provide specific, actionable suggestions to fix the deployment issues
            4. Suggest preventive measures to avoid similar failures
            
            Focus on deployment-specific issues like:
            - Build failures
            - Configuration errors
            - Environment setup problems
            - Dependency issues
            - Infrastructure/deployment script problems
            
            Provide your analysis as inline comments on the relevant code sections when possible. 

          claude_args: |
            --model eu.anthropic.claude-sonnet-4-20250514-v1:0
            --allowedTools "mcp__github_inline_comment__create_inline_comment,Bash(gh pr comment:*),Bash(gh pr diff:*),Bash(gh pr view:*),Bash(gh run view:*),Bash(gh run download:*)"
